// <auto-generated />
using System;
using Ecssr.Demo.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecssr.Demo.Infrastructure.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    partial class NewsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecssr.Demo.Infrastructure.Persistence.Models.News", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Ecssr.Demo.Infrastructure.Persistence.Models.NewsDownload", b =>
                {
                    b.Property<int>("NewsDownloadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsDownloadId"));

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<string>("DownloadFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NewsDownloadId");

                    b.HasIndex("NewsId");

                    b.ToTable("NewsDownloads");
                });

            modelBuilder.Entity("Ecssr.Demo.Infrastructure.Persistence.Models.NewsDownload", b =>
                {
                    b.HasOne("Ecssr.Demo.Infrastructure.Persistence.Models.News", "News")
                        .WithMany("NewsDownloads")
                        .HasForeignKey("NewsId");

                    b.Navigation("News");
                });

            modelBuilder.Entity("Ecssr.Demo.Infrastructure.Persistence.Models.News", b =>
                {
                    b.Navigation("NewsDownloads");
                });
#pragma warning restore 612, 618
        }
    }
}
